name: Run nf-test
on:
  push:
    branches:
      - dev
      - main
  pull_request:

jobs:
  nf-test:
    runs-on: ubuntu-latest
    name: nf-test
    strategy:
      fail-fast: false
      matrix:
        profile: ["docker", "singularity", "conda"]
        exclude:
          - profile: "conda"
    env:
      NXF_ANSI_LOG: false
    steps:
      - uses: actions/checkout@v4
      - uses: nf-core/setup-nextflow@v1
      - uses: nf-core/setup-nf-test@v1

      - name: Setup apptainer
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.1.2

      - name: Run nf-test
        run: |
          nf-test test --profile=${{ matrix.profile }} --verbose
